// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
		int n= Integer.parseInt(args[0]);
		int countBig= 0;
		int countSmall= 0;
		double random= 0;
		for(int i=0;i<n;i++)
		{
			random= Math.random();
			if (random>0.5)
			{
				countBig++;
			}
			else if (random<=0.5)
			{
				countSmall++;
			}
		}
		if(countSmall!=0)
		{
			System.out.println("> 0.5: "+countBig+" times");
			System.out.println("<= 0.5: "+countSmall+" times");
			System.out.println("Ratio: "+(double)countBig/countSmall);
		}
	   
	}
}
